# Generated by Django 3.2.16 on 2022-10-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Band',
        ),
    ]
