# Generated by Django 3.2.16 on 2022-10-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdb', '0002_delete_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('frequency_lo', models.FloatField()),
                ('frequency_hi', models.FloatField()),
                ('licensetype', models.ManyToManyField(to='rdb.LicenseType')),
            ],
        ),
    ]
