# Generated by Django 3.2.16 on 2022-10-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdb', '0003_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplexFrequencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_freq', models.FloatField()),
                ('out_freq', models.FloatField()),
                ('tags', models.ManyToManyField(to='rdb.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Repeater',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rdb.node')),
                ('access_information', models.TextField()),
                ('freq', models.ManyToManyField(to='rdb.DuplexFrequencyPair')),
            ],
            bases=('rdb.node',),
        ),
    ]
