# Generated by Django 3.2.16 on 2022-10-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdb', '0004_duplexfrequencypair_repeater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='add',
            new_name='added',
        ),
    ]
